step = "predict"

[preprocess]
net = "yolo"
src_path = "datasets/MSLesSeg-Dataset"
dst_path = "datasets/yolo_single"
resize = "256x256"
# super_scale = 2
# resize_method = "bilinear"
split = 0.8

[train]
net = "yolo"
src_path = "datasets/yolo_single"
dst_path = "results/yolo_res_single"
batch_size = 8
epochs = 25
learning_rate = 0.001
limit_resources = true

# [predict]
# net = "yolo"
# src_path = "datasets/yolo_single"
# dst_path = "results/yolo/yolo_res_single/predictions"
# model_path = "results/yolo/yolo_res_single/train/weights/best.pt"

[predict]
net = "unet"
src_path = "datasets/unet_single"
dst_path = "results/unet/unet_res_single/predictions"
model_path = "results/unet/unet_res_single/models/unet_model.pth"

[evaluate]
net = "unet"
model_path = "unet_res_single/models/unet_model.pth"
src_path = "results/datasets/unet_single"