[tool.mypy]
python_version = "3.13"
exclude = "^venv/|steps/preprocessing/align_mri_and_mask.py|steps/preprocessing/clane.py|steps/preprocessing/process_data.py"
ignore_missing_imports = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
warn_unused_ignores = true
warn_return_any = true
warn_redundant_casts = true
warn_unreachable = true
show_error_codes = true
pretty = true
strict = true
plugins = ["numpy.typing.mypy_plugin"]

[[tool.mypy.overrides]]
module = "nibabel"
ignore_errors = true
follow_imports = "skip"

[[tool.mypy.overrides]]
module = "cv2"
ignore_errors = true
follow_imports = "skip"